In [ ]:
import numpy as np

List Vs Numphy -Time Taken

In [ ]:
from time import process_time

Time Taken By a List

In [ ]:
python_list=[i for i in range(10000)]

start_time=process_time()

python_list=[i+5 for i in python_list]

end_time =process_time()

print(end_time-start_time)

0.001466566000000391


Time Taken By Numphy Array

In [ ]:
np_array=np.array([i for i in range(10000)])

start_time=process_time()

np_array+=5    #np_array=np_array+5

end_time =process_time()

print(end_time-start_time)

0.0009825559999994127


Numphy Arrays

In [6]:
#list
list1=[1,2,3,4,6]
print(list1)
type(list1)

[1, 2, 3, 4, 6]


list

In [8]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [9]:
#multi dimentional arrays

In [12]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)


[[1 2 3 4]
 [5 6 7 8]]


In [13]:
b.shape


(2, 4)

initial placeholders in numphy arrays


In [14]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [16]:
#arrays of all zeros
d=np.zeros((4,6))
print(d)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [17]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [18]:
#create an identity matrix

a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [20]:
#create a nuphy araray with random values

b=np.random.random((3,4))
print(b)

[[0.59615443 0.04511317 0.26452644 0.25650345]
 [0.20377288 0.1531035  0.28823523 0.5019276 ]
 [0.95310916 0.78116583 0.3096891  0.20557398]]


In [21]:
#random integer values generate within spacific range
c=np.random.randint(10,100,(3,5))
print(c)

[[59 27 69 84 63]
 [79 61 69 37 91]
 [41 70 80 65 35]]


In [23]:
#array of evenly spaced ---first to range,last is number of value we want between that range
d=np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]
